### ISSUE TITLE
bug_layouts/static_pages.html.erbのページにアクセスした際にJSでエラーが生じる

### ISSUE THREAD

**Issue by tanktabox** [tanktabox/bean_stamp#37]
# バグ報告

## 概要
- エラー文
```
Uncaught TypeError: Cannot set properties of null (setting 'onclick')
    at HTMLDocument.<anonymous> (hamburger.js:3:16)
    at o.dispatch (turbolinks.js:75:40)
    at e.notifyApplicationAfterPageLoad (turbolinks.js:994:43)
    at e.visitCompleted (turbolinks.js:1007:23)
    at t.complete (turbolinks.js:782:207)
    at t.<anonymous> (turbolinks.js:812:122)
    at turbolinks.js:862:40
```

- 該当コード
```
document.addEventListener("turbolinks:load", function () {
  const hamburgerBtn = document.getElementById("hamburger-btn");
  hamburgerBtn.onclick = function () {
    document.querySelector("body").classList.toggle("drawer-open");
    document.getElementById("drawer-open-btn").classList.toggle("hidden");
    document.getElementById("drawer-close-btn").classList.toggle("hidden");
  };
});
```

## 原因
- static_page.html.erbをレイアウトとするページにはhumburger-btnのIDを持った要素が存在していないのが原因だと考えられる

## 修正案
-  条件分岐で該当部がないページでは処理を抜けるように修正する

**Comment by tanktabox** [comment]
SPAにしたことでエラーの部分は使用しなくなった
